name        = "Simplicity"
license     = "MIT"
licenselink = "https://github.com/eshlox/simplicity/blob/master/LICENSE"
description = "Simple theme with clean typography."
homepage    = "https://github.com/eshlox/simplicity"
tags        = ["blog", "responsive", "minimal"]
features    = ["disqus", "lightbox"]
min_version = "0.30.2"

[author]
  name      = "Przemysław Kołodziejczyk"
  homepage  = "https://eshlox.net"
